[tool.poetry]
name = "typical"
packages = [{include = "typic"}]
version = "2.0.16"
description = "Typical: Python's Typing Toolkit."
authors = ["Sean Stewart <sean_stewart@me.com>"]
license = "MIT"
readme = "mkdocs/index.md"
repository = "https://github.com/seandstewart/typical"
keywords = ["typing", "data", "annotations", "validation", "json-schema"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
    "Typing :: Typed",
]
include = ["README.md", "LICENSE"]
exclude = ["tests", "docs", "docsrc", "benchmark"]

[tool.poetry.dependencies]
python = "^3.6.1"
inflection = "^0.3.1"
pendulum = "^2.0"
typing-extensions = {version = "^3.7", python = "~3.7"}
dataclasses = {version = "*", python = "~3.6"}
fastjsonschema = {version = "^2.14", optional = true}
ujson = {version = "^2.0.2", optional = true}
marshmallow = {version = "^3.2", optional = true}
toastedmarshmallow = {version = "^2.15", optional = true}
djangorestframework = {version = "^3.10", optional = true}
pydantic = {version = "^1.0", extras = ["email"], optional = true}
django = {version = "^2.2", optional = true}
sqlalchemy = {version = "^1.3.13", optional = true}
pandas = {version = "^1.0.3", optional = true}
flake8 = {version = "^3.7.9", optional = true}
mypy = {version = "^0.761", optional = true}
black = {version = "19.10b0", allow-prereleases = true, optional = true}
mkdocs = {version = "^1.1", optional = true}
mkdocs-material = {version = "^4.6.3", optional = true}
mkdocs-awesome-pages-plugin = {version = "^2.2.1", optional = true}
pymdown-extensions = {version = "^6.3", optional = true}
fontawesome-markdown = {version = "^0.2.6", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
black = {version = "19.10b0", allow-prereleases = true}
pre-commit = "^1.19"
pytest-benchmark = {version = "^3.2", extras = ["histogram"]}
marshmallow = "^3.2"
toastedmarshmallow = "^2.15"
djangorestframework = "^3.10"
pydantic = {version = "^1.0", extras = ["email"]}
django = "^2.2"
flake8 = "^3.7.9"
mypy = "^0.761"
ujson = "^2.0.2"
sqlalchemy = "^1.3.13"
sqlalchemy-stubs = "^0.3"
mkdocs = "^1.1"
mkdocs-material = "^4.6.3"
mkdocstrings = "^0.9.1"
pymdown-extensions = "^6.3"
fontawesome-markdown = "^0.2.6"
mkdocs-awesome-pages-plugin = "^2.2.1"
pandas = "^1.0.3"

[tool.poetry.extras]
schema = ["fastjsonschema"]
json = ["ujson"]
tests = [
    "fastjsonschema",
    "ujson",
    "marshmallow",
    "toastedmarshmallow",
    "djangorestframework",
    "pydantic",
    "django",
    "sqlalchemy",
    "pandas",
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
]
lint = ["mypy", "flake8", "black"]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-awesome-pages-plugin",
    "pymdown-extensions",
    "fontawesome-markdown",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
